// Route manifest generator: scans ../src/app/api/**/route.js and emits
// src/routes-manifest.ts. Re-run via `bun run gen-routes` after API files change.
import { readdir, writeFile, stat } from "node:fs/promises";
import { join, relative, dirname, sep } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const API_ROOT = join(HERE, "..", "vendor", "app", "api");
const OUT = join(HERE, "routes-manifest.ts");

const METHOD_RE = /export\s+(?:async\s+)?function\s+(GET|POST|PUT|DELETE|PATCH|OPTIONS|HEAD)\s*\(/g;
const CONST_RE = /export\s+const\s+(GET|POST|PUT|DELETE|PATCH|OPTIONS|HEAD)\s*=/g;
const REEXPORT_RE = /export\s*\{([^}]*)\}\s*(from\s*["'][^"']+["'])?/g;
const KNOWN_METHODS = new Set(["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD"]);

function parseMethods(src) {
  const found = new Set();
  for (const m of src.matchAll(METHOD_RE)) found.add(m[1]);
  for (const m of src.matchAll(CONST_RE)) found.add(m[1]);
  // export { GET, OPTIONS } from "./models/route"  /  export { GET as GET }
  for (const m of src.matchAll(REEXPORT_RE)) {
    for (const part of m[1].split(",")) {
      const alias = part.trim().split(/\s+as\s+/i).pop().trim();
      if (KNOWN_METHODS.has(alias)) found.add(alias);
    }
  }
  return [...found];
}

async function walk(dir, out) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) await walk(p, out);
    else if (e.isFile() && e.name === "route.js") out.push(p);
  }
}

function toNextPath(file) {
  const rel = relative(API_ROOT, dirname(file));
  const segs = rel === "" ? [] : rel.split(sep);
  return "/api/" + segs.join("/");
}

function parseParams(nextPath) {
  const params = [];
  for (const seg of nextPath.split("/")) {
    const m = /^\[(\.\.\.)?([^\]]+)\]$/.exec(seg);
    if (m) params.push({ name: m[2], catchAll: Boolean(m[1]) });
  }
  return params;
}

const files = [];
await walk(API_ROOT, files);
files.sort();

const { readFile } = await import("node:fs/promises");
const entries = [];
for (const file of files) {
  const src = await readFile(file, "utf8");
  const methods = parseMethods(src);
  if (methods.length === 0) continue;
  const nextPath = toNextPath(file);
  const rel = "./" + relative(HERE, file).split(sep).join("/");
  entries.push({ file: rel, nextPath, methods, params: parseParams(nextPath) });
}

const totalMethods = entries.reduce((n, e) => n + e.methods.length, 0);
const body = `// AUTO-GENERATED by src/scan.ts — do not hand-edit.
// ${entries.length} route files, ${totalMethods} method handlers.
export interface RouteEntry {
  file: string;
  nextPath: string;
  methods: string[];
  params: { name: string; catchAll: boolean }[];
}
export const ROUTES: RouteEntry[] = ${JSON.stringify(entries, null, 2)};
`;

await writeFile(OUT, body);
console.log(`wrote ${OUT}: ${entries.length} files, ${totalMethods} handlers`);
